language: node_js
services:
  - docker

before_install:
  - docker build -t gunavathiduraisamy/reactapp -f Dockerfile.dev .
  
script:
  - docker run gunavathiduraisamy/reactapp npm run test -- --coverage
